apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: loservijay/ecommerce-project-mern:latest
        ports:
        - containerPort: 5000
